### ISSUE TITLE
Cannot GET /socket.io/

### ISSUE THREAD

**Issue by vkarakaya** [GlowstoneHosting/Glowstone#8]
![image](https://user-images.githubusercontent.com/37079672/58206720-f15ae180-7ce9-11e9-987c-ec3efe8d6d65.png)

**Comment by Deudly** [comment]
Hey

Thanks for showing interest on the project. However, the project has a lot of vulnerabilities and issues and needs to be recoded. Said this, it is not intended to be used as it is right now.

Sorry for late response
